apiVersion: 1

datasources:
  - name: WaterQualityDB
    uid: DS_WATERQUALITYDB
    type: postgres
    url: db:5432
    user: wateradmin
    database: waterdb
    secureJsonData:
      password: changeme_db_password
    jsonData:
      database: waterdb
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true